apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logos.fullname" . }}-config
  labels:
    {{- include "logos.labels" . | nindent 4 }}
data:
  PENPOT_PUBLIC_URI: {{ .Values.global.publicUri | quote }}
  PENPOT_TELEMETRY_ENABLED: {{ ternary "true" "false" .Values.global.telemetryEnabled | quote }}
  PENPOT_SMTP_DEFAULT_FROM: {{ .Values.backend.smtp.from | quote }}
  PENPOT_SMTP_DEFAULT_REPLY_TO: {{ .Values.backend.smtp.replyTo | quote }}
  PENPOT_SMTP_HOST: {{ .Values.backend.smtp.host | quote }}
  PENPOT_SMTP_PORT: {{ printf "%v" .Values.backend.smtp.port | quote }}
  PENPOT_SMTP_TLS: {{ ternary "true" "false" .Values.backend.smtp.tls | quote }}
  PENPOT_SMTP_SSL: {{ ternary "true" "false" .Values.backend.smtp.ssl | quote }}
