{{- if .Values.exporter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logos.fullname" . }}-exporter
  labels:
    {{- include "logos.labels" . | nindent 4 }}
    app.kubernetes.io/component: exporter
spec:
  replicas: {{ .Values.exporter.replicaCount }}
  selector:
    matchLabels:
      {{- include "logos.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: exporter
  template:
    metadata:
      labels:
        {{- include "logos.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: exporter
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: exporter
          image: "{{ .Values.exporter.image.repository }}:{{ .Values.exporter.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 6061
              name: http
          envFrom:
            - configMapRef:
                name: {{ include "logos.fullname" . }}-config
            - secretRef:
                name: {{ include "logos.fullname" . }}-secret
          readinessProbe:
            httpGet:
              path: {{ .Values.exporter.probes.path }}
              port: http
            initialDelaySeconds: {{ .Values.exporter.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.exporter.probes.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.exporter.probes.path }}
              port: http
            initialDelaySeconds: {{ add .Values.exporter.probes.initialDelaySeconds 10 }}
            periodSeconds: {{ .Values.exporter.probes.periodSeconds }}
          resources:
            {{- toYaml .Values.exporter.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "logos.fullname" . }}-exporter
  labels:
    {{- include "logos.labels" . | nindent 4 }}
    app.kubernetes.io/component: exporter
spec:
  type: {{ .Values.exporter.service.type }}
  selector:
    {{- include "logos.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: exporter
  ports:
    - name: http
      port: {{ .Values.exporter.service.port }}
      targetPort: http
{{- end }}
