{{- if .Values.mailcatch.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logos.fullname" . }}-mailcatch
  labels:
    {{- include "logos.labels" . | nindent 4 }}
    app.kubernetes.io/component: mailcatch
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "logos.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mailcatch
  template:
    metadata:
      labels:
        {{- include "logos.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mailcatch
    spec:
      containers:
        - name: mailcatch
          image: "{{ .Values.mailcatch.image.repository }}:{{ .Values.mailcatch.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.mailcatch.service.smtpPort }}
              name: smtp
            - containerPort: {{ .Values.mailcatch.service.httpPort }}
              name: web
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "logos.fullname" . }}-mailcatch
  labels:
    {{- include "logos.labels" . | nindent 4 }}
    app.kubernetes.io/component: mailcatch
spec:
  selector:
    {{- include "logos.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mailcatch
  ports:
    - name: smtp
      port: {{ .Values.mailcatch.service.smtpPort }}
      targetPort: smtp
    - name: web
      port: {{ .Values.mailcatch.service.httpPort }}
      targetPort: web
{{- end }}
