apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logos.fullname" . }}-secret
  labels:
    {{- include "logos.labels" . | nindent 4 }}
type: Opaque
stringData:
  PENPOT_SECRET_KEY: {{ .Values.global.secretKey | quote }}
  PENPOT_DATABASE_URI: {{ printf "postgresql://%s-postgres/%s" (include "logos.fullname" .) .Values.postgres.auth.database | quote }}
  PENPOT_DATABASE_USERNAME: {{ .Values.postgres.auth.username | quote }}
  PENPOT_DATABASE_PASSWORD: {{ .Values.postgres.auth.password | quote }}
  PENPOT_REDIS_URI: {{ printf "redis://%s-valkey/0" (include "logos.fullname" .) | quote }}
  PENPOT_SMTP_USERNAME: {{ .Values.backend.smtp.username | quote }}
  PENPOT_SMTP_PASSWORD: {{ .Values.backend.smtp.password | quote }}
