/**
* @generated by rust/logos-types/src/bin/generate_types.rs
* Source:  rust/logos-types/src/
*
* DO NOT EDIT — run `make generate-rust-types` to regenerate.
*/


export type BlurType = "layer-blur" | "background-blur";

export interface Blur {
  blurType: BlurType;
  value: number;
  /** When `true` the blur is defined but not rendered. */
  hidden: boolean;
}
