/**
* @generated by rust/logos-types/src/bin/generate_types.rs
* Source:  rust/logos-types/src/
*
* DO NOT EDIT — run `make generate-rust-types` to regenerate.
*/


export type GradientType = "linear" | "radial";

export interface GradientStop {
  /** CSS `#rrggbb` hex color string. */
  color: string;
  opacity: number;
  /** Position along the gradient, `[0, 1]`. */
  offset: number;
}

export interface Gradient {
  gradientType: GradientType;
  /** Start point X in shape-local coords `[0, 1]`. */
  startX: number;
  startY: number;
  endX: number;
  endY: number;
  /** Radial gradient width (ignored for linear). */
  width?: number | null;
  stops: Array<GradientStop>;
  opacity: number;
}

/**
 * An RGBA color: hex `#rrggbb` + alpha `[0, 1]`.
 *
 * Optional `refId`/`refFile` link this color to a shared library entry.
 */
export interface Color {
  color: string;
  opacity: number;
  refId?: string | null;
  refFile?: string | null;
  name?: string | null;
  path?: string | null;
}
