/**
* @generated by rust/logos-types/src/bin/generate_types.rs
* Source:  rust/logos-types/src/
*
* DO NOT EDIT — run `make generate-rust-types` to regenerate.
*/


import type { Gradient } from "./color";

export interface FillImage {
  id: string;
  width: number;
  height: number;
  mtype?: string | null;
  name?: string | null;
  keepAspectRatio?: boolean | null;
}

/**
 * Fill applied to a shape.  Shapes carry multiple fills (`Array<Fill>`).
 * Discriminated by `fillType`.
 */
export type Fill =
  | { fillType: "solid";    color: string; opacity: number }
  | { fillType: "gradient"; gradient: Gradient; opacity: number }
  | { fillType: "image";    image: FillImage };
