/**
* @generated by rust/logos-types/src/bin/generate_types.rs
* Source:  rust/logos-types/src/
*
* DO NOT EDIT — run `make generate-rust-types` to regenerate.
*/


/** 2-D point — mirrors `logos_layout::Point`. */
export interface Point {
  x: number;
  y: number;
}

/** Axis-aligned bounding box — mirrors `logos_layout::Rect`. */
export interface Bounds {
  x: number;
  y: number;
  width: number;
  height: number;
}

/**
 * 6-element CSS affine matrix `[a, b, c, d, e, f]`
 * — mirrors `logos_layout::Matrix`.
 */
export type Transform = [number, number, number, number, number, number];
