/**
 * rust-generated/index.ts
 *
 * Public API of the Rust-generated type layer.
 *
 * STRUCTURE:
 *  1. `compat` — Malli-wire-format–compatible surface; backward-compatible with
 *     the old generated/shapes.d.ts.  Use these types everywhere in the React
 *     shell and Zustand stores.
 *  2. Rust-native types — available for WASM interop / render pipeline code that
 *     talks directly to logos-types structs.  These carry camelCase field names
 *     derived from Rust snake_case and may differ structurally from the compat
 *     equivalents.
 *
 * GENERATED by rust/logos-types/src/bin/generate_types.rs (index portion is
 * hand-maintained until the generator grows a dependency-aware emit stage).
 * Run `make generate-rust-types` to regenerate the leaf modules, then review
 * this file for any new additions.
 */

// ── (1) Malli-compat surface ─────────────────────────────────────────────────
// Re-exports Point, Bounds, Transform, HorizontalConstraint, VerticalConstraint,
// HexColor, BlendMode, GradientStop, LinearGradient, RadialGradient, Gradient,
// ImageFill, StrokeType, StrokeCap, StrokePosition, Stroke, ShadowType, Shadow,
// Blur, BoolType, GrowType, all layout types, CanonicalShape, CanonicalShapeType.
export * from "./compat";

// ── (2) Rust-native types not present in the compat surface ──────────────────

// color.ts — Rust RGBA Color + single Gradient struct with `gradientType`
// discriminant.  Named GradientType / RustGradient / RustGradientStop to avoid
// shadowing the Malli Gradient / GradientStop in compat.
export type { GradientType, Color }                                   from "./color";
export type { Gradient as RustGradient, GradientStop as RustGradientStop } from "./color";

// stroke.ts — Rust Stroke has `strokeColor`, `strokeOpacity` etc.
export type { StrokeStyle }                                           from "./stroke";
export type { Stroke as RustStroke }                                  from "./stroke";

// shadow.ts — Rust Shadow has nested Color + offsetX/offsetY.
export type { Shadow as RustShadow }                                  from "./shadow";

// blur.ts — BlurType enum + Rust Blur (has `blurType` field).
export type { BlurType }                                              from "./blur";
export type { Blur as RustBlur }                                      from "./blur";

// fill.ts — Rust Fill discriminated union; FillImage (≈ ImageFill in compat).
export type { FillImage, Fill as RustFill }                           from "./fill";

// shape.ts — Rust Shape is the engine-level record (camelCase fields from
// snake_case, selrect instead of x/y/width/height, etc.).
export type { Constraint, ImageMetadata }                             from "./shape";
export type { Shape as RustShape }                                    from "./shape";
// ShapeType is intentionally excluded here to avoid confusion with
// CanonicalShapeType (Malli) and shapes.ts's own ShapeType (frontend).
// Import directly from "./shape" if you need the Rust ShapeType.

// typography.ts
export type { Typography }                                            from "./typography";

// token.ts
export type { TokenType, Token, TokenGroup, TokensLib }              from "./token";
