/**
* @generated by rust/logos-types/src/bin/generate_types.rs
* Source:  rust/logos-types/src/
*
* DO NOT EDIT — run `make generate-rust-types` to regenerate.
*/


import type { Color } from "./color";

export type ShadowStyle = "drop-shadow" | "inner-shadow";

export interface Shadow {
  style: ShadowStyle;
  color: Color;
  offsetX: number;
  offsetY: number;
  blur: number;
  spread: number;
  /** When `true` the shadow is defined but not rendered. */
  hidden: boolean;
}
