/**
* @generated by rust/logos-types/src/bin/generate_types.rs
* Source:  rust/logos-types/src/
*
* DO NOT EDIT — run `make generate-rust-types` to regenerate.
*/


import type { Bounds, Point, Transform } from "./geometry";
import type { Fill } from "./fill";
import type { Stroke } from "./stroke";
import type { Shadow } from "./shadow";
import type { Blur } from "./blur";

export type ShapeType =
  | "frame" | "rect" | "circle" | "path" | "image"
  | "text"  | "group" | "bool"  | "component";

export type ConstraintH = "left" | "right" | "leftright" | "center" | "scale";
export type ConstraintV = "top"  | "bottom" | "topbottom" | "center" | "scale";

export interface Constraint {
  h: ConstraintH;
  v: ConstraintV;
}

export type BoolType = "union" | "difference" | "intersection" | "exclusion";

export interface ImageMetadata {
  id: string;
  width: number;
  height: number;
  mtype?: string | null;
}

/**
 * Core domain object: every visible element in a Logos design is a Shape.
 *
 * Rust-authoritative definition — replaces `common/types/shape.cljc`.
 */
export interface Shape {
  id: string;
  shapeType: ShapeType;
  name: string;

  // Geometry
  selrect: Bounds;
  transform: Transform;
  transformInverse: Transform;
  rotation: number;
  points?: Array<Point> | null;

  // Hierarchy
  parentId?: string | null;
  frameId?: string | null;
  /** Ordered child shape IDs (Frame / Group / Bool only). */
  shapes: Array<string>;

  // Visibility
  hidden: boolean;
  opacity: number;
  maskedGroup: boolean;

  // Appearance
  fills: Array<Fill>;
  strokes: Array<Stroke>;
  shadow: Array<Shadow>;
  blur: Array<Blur>;

  // Border radius
  rx?: number | null;
  ry?: number | null;
  r1?: number | null;
  r2?: number | null;
  r3?: number | null;
  r4?: number | null;

  // Constraints
  constraintsH: ConstraintH;
  constraintsV: ConstraintV;
  fixedScroll: boolean;

  // Component link
  componentId?: string | null;
  componentFile?: string | null;
  componentRoot: boolean;
  mainInstance: boolean;

  // Image-specific
  metadata?: ImageMetadata | null;

  // Bool-specific
  boolType?: BoolType | null;

  // Plugin / extension data
  pluginData: Record<string, string>;
}
