/**
* @generated by rust/logos-types/src/bin/generate_types.rs
* Source:  rust/logos-types/src/
*
* DO NOT EDIT — run `make generate-rust-types` to regenerate.
*/


export type StrokeStyle = "solid" | "dashed" | "dotted" | "mixed" | "svg" | "none";

export type StrokeCap =
  | "none" | "line" | "triangle" | "square" | "circle" | "diamond" | "round";

export type StrokePosition = "center" | "inner" | "outer";

export interface Stroke {
  strokeColor: string;
  strokeOpacity: number;
  strokeWidth: number;
  strokeStyle: StrokeStyle;
  strokePosition: StrokePosition;
  strokeCapStart: StrokeCap;
  strokeCapEnd: StrokeCap;
}
