/**
* @generated by rust/logos-types/src/bin/generate_types.rs
* Source:  rust/logos-types/src/
*
* DO NOT EDIT — run `make generate-rust-types` to regenerate.
*/


export type TokenType =
  | "color" | "spacing" | "sizing" | "font-family" | "font-size"
  | "font-weight" | "font-style" | "line-height" | "letter-spacing"
  | "opacity" | "rotation" | "border-radius" | "stroke-width"
  | "duration" | "timing" | "dimension" | "shadow" | "blur"
  | "typography" | "other";

export interface Token {
  id: string;
  /** Slash-delimited name path, e.g. `"colors/primary"`. */
  name: string;
  tokenType: TokenType;
  value: string;
  description?: string | null;
}

export interface TokenGroup {
  name: string;
  tokens: Record<string, Token>;
}

/**
 * Top-level design-token library for a file.
 * Replaces `common/types/tokens_lib.cljc`.
 */
export interface TokensLib {
  sets: Record<string, Record<string, Token>>;
  activeSets: Array<string>;
}
