/**
* @generated by rust/logos-types/src/bin/generate_types.rs
* Source:  rust/logos-types/src/
*
* DO NOT EDIT — run `make generate-rust-types` to regenerate.
*/


/**
 * A named, reusable text-formatting preset stored in the shared library.
 * Replaces `common/types/typography.cljc`.
 */
export interface Typography {
  id: string;
  name: string;
  fontFamily: string;
  fontId?: string | null;
  fontVariantId: string;
  fontStyle: string;
  fontWeight: string;
  fontSize: string;
  lineHeight: string;
  letterSpacing: string;
  textTransform: string;
  path?: string | null;
}
